# Generated by Django 3.2 on 2023-10-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
