# Generated by Django 3.2 on 2023-10-31 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobListing',
            new_name='JobList',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
